### ISSUE TITLE
Feature: PNG 48x48 icon

### ISSUE THREAD

**Issue by jj-uk** [jaymoulin/docker-google-music-uploader#10]
I use this with unRAID. The docker system allows an icon to be displayed next to the docker containers.

Any chance of a 48x48px PNG icon of the google play upload icon?

**Comment by jaymoulin** [comment]
Could you please send some documentation about this? I don't see how a docker image could be related with a graphical image

**Comment by jaymoulin** [comment]
Looks like you have to configure it in your application. https://lime-technology.com/forums/topic/38582-plug-in-community-applications/

**Comment by jj-uk** [comment]
Yes. I have to specify the URL of an icon for use by the docker container. As this is the docker I'm using, it would make sense for me to use an icon hosted in the same location as the code.

**Comment by jj-uk** [comment]
Please?

**Comment by jaymoulin** [comment]
Your request is invalid and has nothing to do with this project. if you want an image, just google it and add it to your configuration
