### ISSUE TITLE
Consider changing the default for remove to false

### ISSUE THREAD

**Issue by guyspr** [jaymoulin/docker-google-music-uploader#6]
I found this docker, and it's really neat. Only I would like to ask you to consider changing the default for file removal to false. Removing files seems to be a rather big thing which you do not want to default to. I want to keep my local copy and not remove the files after an upload. I think some people might miss this and question where their media library went.

**Comment by jaymoulin** [comment]
https://github.com/jaymoulin/docker-google-music-uploader#environment-variables

You can change it by passing the `-e REMOVE=false` parameter. This is a choice for files to be deleted. I know this was not the default behaviour of former google music manager by google but I thought people using that image would use it to keep their music library on the cloud only.

At the beginning of this projet, the image was only available for Raspberry Pi and I was thinking that keeping all your music library on that kind of device wasn't a thing you wanted to do.

**Comment by guyspr** [comment]
I did see the setting, and I used it. But in my eyes it might be better to default to false for file removal, and explicitly say you want to delete files with `-e REMOVE=false`. I understand where you are coming from though.

**Comment by jaymoulin** [comment]
I understand the concept. That kind of update requires a major update on 2 projects. I don't think this "feature" ONLY could justify the version change without another feature with. 
Please suggest/PR me something more so I can release a major update that would justify that kind of release
